chore(ci): Let all CIs fail if corresponding image does not comply with dockle
Signed-off-by: Thorsten Hans <thorsten.hans@gmail.com>

diff --git a/.github/templates/build-and-push/action.yml b/.github/templates/build-and-push/action.yml
--- a/.github/templates/build-and-push/action.yml
+++ b/.github/templates/build-and-push/action.yml
@@ -73,11 +73,11 @@ runs:
         labels: |
           containers
           security
-      #- name: Fail if Vulnerable
-      #  if: contains(env.DOCKLE_RESULT, 'WARN') || contains(env.DOCKLE_RESULT, 'FATAL')
-      #  run: |
-      #    echo "::error ::Please check scan results (see corresponding issue)"
-      #    exit 1
+    - name: Fail if Vulnerable
+      if: contains(env.DOCKLE_RESULT, 'WARN') || contains(env.DOCKLE_RESULT, 'FATAL')
+      run: |
+        echo "::error ::Please check scan results (see corresponding issue)"
+        exit 1
     - name: Push Docker Image
       if: ${{ success() }}
       shell: bash
